stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKERHUB_USERNAME: $DOCKER_HUB_USERNAME
  DOCKERHUB_PASSWORD: $DOCKER_HUB_ACCESS_TOKEN 
  DOCKERHUB_REPO: $CI_PROJECT_NAMESPACE-$CI_PROJECT_NAME
  DOCKER_COMPOSE_CONTAINER_NAME: $CI_PROJECT_NAME
  SSH_PRIVATE_KEY: $SSH_KEY_DEPLOY
services:
  - docker:dind

build:
  stage: build
  script:
    - docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"
    - docker build -t $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:latest .
    - docker push $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:latest
  only:
    - dev


deploy:
  stage: deploy
  script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | base64 -d > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H 147.45.225.75 >> ~/.ssh/known_hosts
    - |
      ssh user@your-server-address << 'EOF'
      if ! command -v docker &> /dev/null
      then
          echo "Docker could not be found"
          exit 1
      fi
      docker login -u $DOCKERHUB_USERNAME --password-stdin <<< "$DOCKERHUB_PASSWORD"
      docker pull $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:latest
      docker-compose -f /root/docker-compose.yml up --no-deps -d $DOCKER_COMPOSE_CONTAINER_NAME
      docker system prune -f
      docker logout
      EOF
  only:
    - production
