stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKERHUB_USERNAME: $DOCKER_HUB_USERNAME
  DOCKERHUB_PASSWORD: $DOCKER_HUB_ACCESS_TOKEN 
  DOCKERHUB_REPO: $CI_PROJECT_NAMESPACE-$CI_PROJECT_NAME
  DOCKER_COMPOSE_CONTAINER_NAME: $CI_PROJECT_NAME
  SSH_PRIVATE_KEY: $SSH_PRIVATE_KEY
services:
  - docker:dind

build:
  stage: build
  script:
    - docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"
    - docker build -t $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:latest .
    - docker push $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:latest
  only:
    - dev


deploy:
  stage: deploy
  script:
    - mkdir -p ~/.ssh
    - echo -n $SSH_PRIVATE_KEY | base64 -d > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H 147.45.225.75 >> ~/.ssh/known_hosts
    - ssh root@147.45.225.75 "docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
                                    docker pull $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:latest && \
                                    docker-compose -f /root/docker-compose.yml up --no-deps -d $DOCKER_COMPOSE_CONTAINER_NAME && \
                                    docker system prune -f && \
                                    docker logout"
  only:
    - production
