stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKERHUB_USERNAME: $DOCKER_HUB_USERNAME
  DOCKERHUB_PASSWORD: $DOCKER_HUB_ACCESS_TOKEN 
  DOCKERHUB_REPO: $CI_PROJECT_NAMESPACE-$CI_PROJECT_NAME
  SSH_PRIVATE_KEY: $SSH_PRIVATE_KEY 
services:
  - docker:dind

before_script:
  - docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"

build:
  stage: build
  script:
    - docker build -t $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:latest .
    - docker push $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:latest

deploy:
  stage: deploy
  script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H your-server-address >> ~/.ssh/known_hosts
    - ssh user@your-server-address "docker pull $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:latest && \
                                    docker-compose -f /path/to/docker-compose.yml up --no-deps -d web && \
                                    docker system prune -f"
  only:
    - production
