version: "3.8"

services:
  frontend:
    container_name: aleelo-front
    build: .
    restart: always #change if you don't want your container restarting test
    environment:
      - NODE_ENV=production
    ports:
      - 3000:3000
